name: Insecure Bank CI with Coverity hardcoded

on:
  push:
    branches: [ coverity-hardcoded ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Convert Coverity Results to SARIF
        uses: gautambaghel/coverity-scan-results-to-sarif@e8eb7a61f9180fcaab6f78212ad1397af11c48bb
        with:
          pipeline-results-json: coverity-results-desktop.json
          output-results-sarif: coverity-results.sarif
      - name: Print SARIF
        run: cat coverity-results.sarif
      - name: Upload SARIF file to GitHub UI
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: coverity-results.sarif
