# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Insecure Bank CI with Coverity on Private runner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    
    env:
      COVBIN: /opt/coverity/analysis/2020.06/bin
      COVERITY_SERVER_URL: http://coverity.synopsys-alliances.com/
      COVERITY_STREAM: insecure-bank
      COV_USER: gautam
      COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
      BLDCMD: mvn -B clean compile
      CHECKERS: --all --webapp-security

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Coverity BAC
      run: |
        rm -rf idir
        $COVBIN/cov-configure --java
        $COVBIN/cov-build --dir idir $BLDCMD
        $COVBIN/cov-analyze --dir idir --ticker-mode none --strip-path $PWD $CHECKERS
        $COVBIN/cov-commit-defects --dir idir --ticker-mode none --url $COVERITY_SERVER_URL --stream $COVERITY_STREAM
        $COVBIN/cov-format-errors --dir idir --json-output-v7 coverity-results.json
    - name: Convert Coverity Results to SARIF
      uses: gautambaghel/coverity-scan-results-to-sarif@1.0.0
      with:
        pipeline-results-json: coverity-results.json
        output-results-sarif: coverity-results.sarif
    - name: Upload SARIF file to GitHub UI
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: coverity-results.sarif
